lesson8
NataliaKrolikova/TMS_Natalia2 pull request #1
Opened 2021-02-09 15:17 UTC by NataliaKrolikova

2021-02-10 18:23 UTC, KonstantinLeineveber commented on lesson8/src/Metod19.java
> +                if(str.charAt(i) == ' '){
По условию задачи здесь возможно слова могут быть разделены несколькими пробелами. А также пробелы могут быть вначале и конце строки. У меня было похоже написано и Рома сказал переделать через токинайзер или паттерны и матчеры

2021-02-10 18:25 UTC, KonstantinLeineveber commented on lesson8/src/Metodichka23.java
> +        str = str.replaceAll("<((p(\\s(id)?\\s?=\\s?\\W\\S+\\W)?)|(p.+?))>", "<p>");
Здесь мне тоже сказали придумать универсальное решение

2021-02-10 18:26 UTC, KonstantinLeineveber commented on lesson8/src/Metodichka22.java
> +        Pattern pat = Pattern.compile("0[Xx](([a-fA-F]|[0-9]){0,2}){1,3}");
https://javarush.ru/quests/lectures/questsyntaxpro.level09.lecture01

2021-02-10 18:33 UTC, KonstantinLeineveber requested changes
Глянь комменты

2021-02-12 15:27 UTC, NataliaKrolikova commented on lesson8/src/Metod19.java
> +                if(str.charAt(i) == ' '){
Это задача в теме, в которой про это ничего не рассказано. Поэтому оставлю так.

2021-02-12 15:27 UTC, NataliaKrolikova commented on lesson8/src/Metodichka22.java
> +        Pattern pat = Pattern.compile("0[Xx](([a-fA-F]|[0-9]){0,2}){1,3}");
Здесь мне не понятно что не так

2021-02-12 18:30 UTC, KonstantinLeineveber commented on lesson8/src/Metodichka22.java
> +        Pattern pat = Pattern.compile("0[Xx](([a-fA-F]|[0-9]){0,2}){1,3}");
У тебя может быть такое число 0xC934E5D372B2AB6D0A50B9F0341A00ed029bdc15

2021-02-13 15:31 UTC, RomanKashenok requested changes

2021-02-13 15:31 UTC, RomanKashenok commented on lesson8/src/Metod18.java
> +                if (symbol == ',' || symbol == '.' || symbol == '-') {
есть много других знаков препинания. Попробуй с помощью регулярного выражения (для пунктуации есть свое отдельное даже)

2021-02-13 15:31 UTC, RomanKashenok commented on lesson8/src/Metod19.java
> +                if(str.charAt(i) == ' '){
Ну вообще Костя прав. Строка может быть разная вот в этой строке у тебя будет ошибка:
"В этой строке,например,ровно семь слов  . "

2021-02-13 15:31 UTC, RomanKashenok commented on lesson8/src/Metod20.java
> +        str = str.replaceAll("[!.,:;-]", "");
попробуй со строкой из предыдущего комментария

2021-02-13 15:31 UTC, RomanKashenok commented on lesson8/src/Metod21.java
> +        long startTime = System.currentTimeMillis();
переменная не используется

2021-02-13 15:31 UTC, RomanKashenok commented on lesson8/src/Metod21.java
> +        long startTime2 = System.currentTimeMillis();
можно переиспользовать переменную startTime1

2021-02-13 15:31 UTC, RomanKashenok commented on lesson8/src/Metod21.java
> +        long end2 = System.currentTimeMillis();
можно переиспользовать ранее созданную переменную

2021-02-13 15:31 UTC, RomanKashenok commented on lesson8/src/Metodichka22.java
> +        Pattern pat = Pattern.compile("0[Xx](([a-fA-F]|[0-9]){0,2}){1,3}");
Ну вообще не может ))) 0xFFFFFF может ))
по сути регулярка близка к истине, но не верная по итогу

2021-02-13 15:31 UTC, RomanKashenok commented on lesson8/src/Metodichka23.java
> +        str = str.replaceAll("<((p(\\s(id)?\\s?=\\s?\\W\\S+\\W)?)|(p.+?))>", "<p>");
как по мне - вполне универсальная регулярка. Но можно было обойтись только второй её частью - и то, чисто для читабельности

2021-02-19 14:46 UTC, merged